version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      # Descomente se sua app usar PORT explicitamente (ajuste se necess√°rio)
      # - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped